#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Best School" before "Hi".

count=1

while [ $count <= 10 ]
do
		  echo "Best School"
			if [ $count == 9]
	 			then
					echo "Hi"
	fi
	 ((count++))
 done
